### ISSUE TITLE
깃허브 Docs를 더 알아보자

### ISSUE THREAD

**Issue by dusunax** [dusunax/exercises#3]
# Github Docs: 새롭게 알게 된 기능들

## 1. Mermaid: 다이어그램을 만들 수 있다

- [링크](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams)
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
```mermaid
graph LR;
doctor--> order & patient
technician --> order
```

## 2. STL 3D 모델을 만들 수 있다 (세상에)
- [링크](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-stl-3d-models)
```stl
solid cube_corner
  facet normal 0.0 -1.0 0.0
    outer loop
      vertex 0.0 0.0 0.0
      vertex 1.0 0.0 0.0
      vertex 0.0 0.0 1.0
    endloop
  endfacet
  facet normal 0.0 0.0 -1.0
    outer loop
      vertex 0.0 0.0 0.0
      vertex 0.0 1.0 0.0
      vertex 1.0 0.0 0.0
    endloop
  endfacet
  facet normal -1.0 0.0 0.0
    outer loop
      vertex 0.0 0.0 0.0
      vertex 0.0 0.0 1.0
      vertex 0.0 1.0 0.0
    endloop
  endfacet
  facet normal 0.577 0.577 0.577
    outer loop
      vertex 1.0 0.0 0.0
      vertex 0.0 1.0 0.0
      vertex 0.0 0.0 1.0
    endloop
  endfacet
endsolid
```

## 3. 색 모델을 표현할 수 있다
- `#ff0000`
- `rgb(0, 255, 255)`
- `rgba(255, 255, 0, 0.5)`

## 4. 레포지토리에 있는 이미지를 사용하려면? => 상대 링크를 써야 한다.
Context | 상대 링크
-- | --
동일한 분기의 .md 파일에서 | /assets/images/electrocat.png
다른 분기의 .md 파일에서 | /../main/assets/images/electrocat.png
리포지토리의 이슈, 끌어오기 요청, 주석에서 | ../blob/main/assets/images/electrocat.png?raw=true
다른 리포지토리의 .md 파일에서 | /../../../../github/docs/blob/main/assets/images/electrocat.png
다른 리포지토리의 이슈, 끌어오기 요청, 주석에서 | ../../../github/docs/blob/main/assets/images/electrocat.png?raw=true

## 5. prefers-color-scheme에 따라 다른 이미지를 표기할 수도 있다.
- [링크](https://docs.github.com/ko/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to)

## 6. 외부 리소스를 참조하도록 자동 링크할 수 있다.
- [링크](https://docs.github.com/ko/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-autolinks-to-reference-external-resources)
```
참조 접두사: JIRA-
대상 URL: https://jira.example.com/issue?query=<num>
미리 보기: JIRA-123은 https://jira.example.com/issue?query=123으로 변환됩니다
```

## 7. 각주를 추가할 수 있다

- wiki에서 지원되지 않음 

Here is a simple footnote[^1].
A footnote can also have multiple lines[^2].

[^1]: My reference.
[^2]: To add line breaks within a footnote, prefix new lines with 2 spaces.
  This is a second line.

## 8. 확장된 기능이 있다.

> [!NOTE]
> Useful information that users should know, even when skimming content.

> [!TIP]
> Helpful advice for doing things better or more easily.

> [!IMPORTANT]
> Key information users need to know to achieve their goal.

> [!WARNING]
> Urgent info that needs immediate user attention to avoid problems.

> [!CAUTION]
> Advises about risks or negative outcomes of certain actions.

> [!Note]
> this is a note

## 9. 토글: 축소된 섹션을 표현할 수 있다

<details>

<summary>Tips for collapsed sections</summary>

### You can add a header

You can add text within a collapsed section. 

You can add an image or a code block, too.

```ruby
   puts "Hello World"
```

</details>

## 10. 코드 스니펫: permanent link를 만들 수 있다.

- 같은 레포에서만 가능
- [링크](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet)

https://github.com/dusunax/exercises/blob/14063ef26b320e21268d086c602095394b9e0f70/009/package.json#L1-L16

### 11. Syntax for GitHub's form schema

- 이슈 템플릿 [링크](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
- Syntax for GitHub's form schema [링크](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)
- #4 

```yaml
- type: textarea
  attributes:
    label: Operating System
    description: What operating system are you using?
    placeholder: "Example: macOS Big Sur"
    value: operating system
  validations:
    required: true
- type: dropdown
  attributes:
    label: Version
    description: What version of our software are you running?
    multiple: false
    options:
      - 1.0.2 (Default)
      - 1.0.3 (Edge)
    default: 0
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Code of Conduct
    description: The Code of Conduct helps create a safe space for everyone. We require
      that everyone agrees to it.
    options:
      - label: I agree to follow this project's [Code of Conduct](link/to/coc)
        required: true
- type: markdown
  attributes:
    value: "Thanks for completing our form!"
```

## More Reference 

- https://leonardomontini.dev/github-issue-form-template/
