### ISSUE TITLE
I am 🌲

### ISSUE THREAD

**Issue by dusunax** [dusunax/exercises#4]
### How are you feeling today?

😄 Happy

### What Happened?

```shell
월요일 좋아
```

### Extra fields

- [X] Take care yourself!
- [X] Good bye🤚

**Comment by dusunax** [comment]
## Schema & Form Render

```yaml
name: Feeling Report
description: How are you today?
title: "I am "
labels: ["feelings"]
assignees:
  - dusunax
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help everyone identify you!
  - type: dropdown
    id: feelings
    attributes:
      label: How are you feeling today?
      options:
        - 😶 Meh
        - 😄 Happy
        - ☹️ Sad
        - 😴 Sleepy
        - 🥳 Excited
        - 😫 Exhausted
        - 😱 Scared
        - 🤬 Angry
        - 😇 Blessed
        - 🥰 Loving
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What Happened?
      description: Today is...
      placeholder: Tell us what happened!
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Extra fields
      options:
        - label: Take care yourself!
          required: true
        - label: Good bye🤚
```

![image](https://github.com/dusunax/exercises/assets/94776135/5db29b54-d1dd-463d-be23-789d7264abd4)
